#!/bin/bash
mkdir $1
cd $1
mkdir src bin headers
printf "int main(int argc, char *argv[])\n{\n\treturn 0;\n}" >> src/main.cpp
printf '
CC=g++-4.9
CFLAGS=-c
SRC=src/*.cpp
HEADERS=headers/*
EXECUTABLE=bin/main

all: compile clean

compile:
	$(CC) $(SRC) -o $(EXECUTABLE)

clean:
	rm -rf *.o
' >> Makefile

ln -sf headers src/headers
