#!/bin/sh
git config --global core.excludesfile ~/.gitignore
git config --global user.name "AJ Almacin"
git config --global user.email "aldrinjerome19@gmail.com"
git config --global alias.co checkout
git config --global alias.stat status
